# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.contact:
        class: AMBundle\Admin\ContactAdmin
        arguments: [~, AMBundle\Entity\Contact, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Contact }
    admin.experience:
        class: AMBundle\Admin\ExperienceAdmin
        arguments: [~, AMBundle\Entity\Experience, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Experience }
    formation.experience:
        class: AMBundle\Admin\FormationAdmin
        arguments: [~, AMBundle\Entity\Formation, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Formation }